// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOyR6up0k7o0aNCfKzTa77_n2fqt7BNAE',
    appId: '1:5599037822:web:bdfdd88f463e68f7c90b2f',
    messagingSenderId: '5599037822',
    projectId: 'poultrybooks-95f59',
    authDomain: 'poultrybooks-95f59.firebaseapp.com',
    storageBucket: 'poultrybooks-95f59.firebasestorage.app',
    measurementId: 'G-13NT9GTNJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsu6I4CM99NkrgJnhrAHKwcnKOzuP-D10',
    appId: '1:5599037822:android:afe02511fd0e1926c90b2f',
    messagingSenderId: '5599037822',
    projectId: 'poultrybooks-95f59',
    storageBucket: 'poultrybooks-95f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_Xc4mKRlrOmPhFE2JDrnpUkdIryecwg',
    appId: '1:5599037822:ios:966190bb3e68a6eac90b2f',
    messagingSenderId: '5599037822',
    projectId: 'poultrybooks-95f59',
    storageBucket: 'poultrybooks-95f59.firebasestorage.app',
    iosBundleId: 'com.example.poultryProfitCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_Xc4mKRlrOmPhFE2JDrnpUkdIryecwg',
    appId: '1:5599037822:ios:966190bb3e68a6eac90b2f',
    messagingSenderId: '5599037822',
    projectId: 'poultrybooks-95f59',
    storageBucket: 'poultrybooks-95f59.firebasestorage.app',
    iosBundleId: 'com.example.poultryProfitCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOyR6up0k7o0aNCfKzTa77_n2fqt7BNAE',
    appId: '1:5599037822:web:71cdbd4e556cdc92c90b2f',
    messagingSenderId: '5599037822',
    projectId: 'poultrybooks-95f59',
    authDomain: 'poultrybooks-95f59.firebaseapp.com',
    storageBucket: 'poultrybooks-95f59.firebasestorage.app',
    measurementId: 'G-GKTCJ39KT5',
  );
}
